#
# Travis configuration guide for R language:
#   https://docs.travis-ci.com/user/languages/r/
#   https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis
#
 language: R
 cache: packages
 
 jobs:
  include:
  - r: 3.1
    warnings_are_errors: false
  - r: 3.2
    warnings_are_errors: false
  - r: 3.3
  - r: 3.4
  - r: release
  - r: devel
  
after_success:
  - Rscript -e 'covr::codecov()'