# Travis configuration guide for R language:
#   https://docs.travis-ci.com/user/languages/r/
#   https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

 language: R
 cache: packages
 warnings_are_errors: false
 
 jobs:
  include:
  - r: 3.4
  - r: release
  - r: devel
  
 env:
   global:
   - _R_CHECK_FORCE_SUGGESTS_=false
  
after_success:
  - Rscript -e 'covr::codecov()'